root_ref.child('slot1').set('0')
# root_ref.child('slot2').set('0')
# root_ref.child('slot3').set('0')
# root_ref.child('slot4').set('0')
# root_ref.child('slot5').set('0')
# root_ref.child('slot6').set('1')